name: CI

on:
  push:
    branches: [master]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2

    - name: Install packages
      run: npm i

    - name: Run unit tests
      run: npm run test
